name: 'Frogo-Admob-Helper'
description: 'Admob Helper for your android apps'
author: 'Muhammad Faisal Amir'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}